### ISSUE TITLE
Add Cluster within documentation generates a heap of new files

### ISSUE THREAD

**Issue by aldebaran30701** [AustralianCyberSecurityCentre/constellation_cyber_plugins#5]
Upon cloning both Constellation-app and constellation_cyber_plugins, I added constellation-app as a cluster to constellation_cyber_plugins. This generated a heap of new files within the wizard.

I feel like the documentation in readme.md could read "add project" instead of add cluster. This would not generate the new files and still leave it working.

I could be wrong but this just seems like a wording issue within the `README.md`

**Comment by ACSCUser2** [comment]
Thanks for your feedback, we have amended the README.md as suggested.
